---
name: Checks

on: [ push, pull_request ]
jobs:
  rtc:
    runs-on: ubuntu-latest
    name: RuboCop TODO
    steps:
      # - name: Start SSH session
      #   uses: luchihoratiu/debug-via-ssh@main
      #   with:
      #     NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}
      #     SSH_PASS: ${{ secrets.SSH_PASS }}
      - uses: luchihoratiu/rtc-action@test
        env:
          RTC_TOKEN: ${{ secrets.RTC_TOKEN }}
          UPDATE_PR: true
